-- PostgreSQL初始化脚本
-- 此脚本会在PostgreSQL容器首次启动时自动执行

-- 创建五笔字符表
CREATE TABLE IF NOT EXISTS wubi_characters (
    id SERIAL PRIMARY KEY,
    character_val VARCHAR(4) NOT NULL UNIQUE,
    wubi_code VARCHAR(8) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建用户表
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建课程表
CREATE TABLE IF NOT EXISTS lessons (
    id SERIAL PRIMARY KEY,
    character_val VARCHAR(32) NOT NULL,
    code VARCHAR(32) NOT NULL,
    description TEXT NOT NULL
);

-- 创建用户进度表
CREATE TABLE IF NOT EXISTS user_progress (
    id SERIAL PRIMARY KEY,
    user_name VARCHAR(64) NOT NULL,
    lesson_id INT NOT NULL,
    accuracy FLOAT NOT NULL,
    score INT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建文章表
CREATE TABLE IF NOT EXISTS articles (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    difficulty VARCHAR(10) DEFAULT 'medium'
);

-- 创建五笔字根表
CREATE TABLE IF NOT EXISTS wubi_roots (
    id SERIAL PRIMARY KEY,
    character_val VARCHAR(32) NOT NULL,
    code VARCHAR(32) NOT NULL,
    position VARCHAR(64) NOT NULL,
    description TEXT
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_wubi_character ON wubi_characters(character_val);
CREATE INDEX IF NOT EXISTS idx_wubi_code ON wubi_characters(wubi_code);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- 插入一些初始数据
INSERT INTO wubi_characters (character_val, wubi_code) VALUES 
('一', 'GGLL'),
('的', 'RQYY'),
('是', 'JGHU'),
('在', 'DFD'),
('不', 'GII'),
('了', 'BNH'),
('有', 'DEF'),
('和', 'TKG'),
('人', 'W'),
('这', 'YPI'),
('中', 'KHK'),
('大', 'DDDD'),
('为', 'YLYI'),
('上', 'HHGG'),
('个', 'WHJ'),
('国', 'LGYI'),
('我', 'TRNT'),
('以', 'NYWY'),
('要', 'SVF'),
('他', 'WBN')
ON CONFLICT (character_val) DO NOTHING;

-- 插入完整的五笔字符数据（包含拼音）
ALTER TABLE wubi_characters ADD COLUMN IF NOT EXISTS pinyin VARCHAR(64) DEFAULT '';

-- 清空现有数据
TRUNCATE TABLE wubi_characters;

-- 插入数据
INSERT INTO wubi_characters (character_val, wubi_code, pinyin) VALUES
('的', 'RQYY', 'de'),
('一', 'GGLL', 'yī'),
('是', 'JGHU', 'shì'),
('在', 'DFD', 'zài'),
('不', 'GII', 'bù'),
('了', 'BNH', 'le'),
('有', 'DEF', 'yǒu'),
('和', 'TKG', 'hé'),
('人', 'W', 'rén'),
('这', 'YPI', 'zhè'),
('中', 'KHK', 'zhōng'),
('大', 'DDDD', 'dà'),
('为', 'YLYI', 'wèi'),
('上', 'HHGG', 'shàng'),
('个', 'WHJ', 'gè'),
('国', 'LGYI', 'guó'),
('我', 'TRNT', 'wǒ'),
('以', 'NYWY', 'yǐ'),
('要', 'SVF', 'yào'),
('他', 'WBN', 'tā'),
('时', 'JFY', 'shí'),
('来', 'GOI', 'lái'),
('用', 'ETH', 'yòng'),
('们', 'WUN', 'men'),
('生', 'TGJ', 'shēng'),
('到', 'GCJH', 'dào'),
('作', 'WTHF', 'zuò'),
('地', 'FBN', 'dì'),
('于', 'GFK', 'yú'),
('出', 'BMK', 'chū'),
('就', 'YIUY', 'jiù'),
('分', 'WVB', 'fēn'),
('对', 'CFY', 'duì'),
('成', 'DNNT', 'chéng'),
('会', 'WFCU', 'huì'),
('可', 'SKD', 'kě'),
('主', 'YGD', 'zhǔ'),
('发', 'NTCY', 'fā'),
('年', 'RHF', 'nián'),
('动', 'FCLN', 'dòng'),
('同', 'MGK', 'tóng'),
('工', 'AAAA', 'gōng'),
('也', 'BNH', 'yě'),
('能', 'CEXX', 'néng'),
('下', 'GHI', 'xià'),
('过', 'FPI', 'guò'),
('自', 'THD', 'zì'),
('面', 'DMJD', 'miàn'),
('起', 'FHN', 'qǐ'),
('如', 'VKG', 'rú'),
('事', 'GKVH', 'shì'),
('理', 'GJFG', 'lǐ'),
('情', 'NGEG', 'qíng'),
('你', 'WQIY', 'nǐ'),
('她', 'VBN', 'tā'),
('它', 'PXB', 'tā'),
('省', 'ITHF', 'shěng'),
('市', 'YMHJ', 'shì'),
('区', 'AQI', 'qū'),
('县', 'EGCU', 'xiàn'),
('乡', 'XTE', 'xiāng'),
('村', 'SFY', 'cūn'),
('家', 'PE', 'jiā'),
('户', 'YNE', 'hù'),
('人', 'W', 'rén'),
('民', 'NAV', 'mín'),
('工', 'AAAA', 'gōng'),
('农', 'PEI', 'nóng'),
('商', 'UMW', 'shāng'),
('学', 'IPBF', 'xué'),
('兵', 'RGWU', 'bīng'),
('男', 'LLB', 'nán'),
('女', 'VVV', 'nǚ'),
('老', 'FTX', 'lǎo'),
('少', 'ITR', 'shào'),
('幼', 'XLN', 'yòu'),
('生', 'TGJ', 'shēng'),
('死', 'GQXB', 'sǐ'),
('病', 'UGMW', 'bìng'),
('残', 'GQGT', 'cán'),
('富', 'PGKL', 'fù'),
('穷', 'PWLB', 'qióng'),
('贵', 'KHGM', 'guì'),
('贱', 'MGT', 'jiàn'),
('美', 'UGDU', 'měi'),
('丑', 'NFD', 'chǒu'),
('善', 'UDUK', 'shàn'),
('恶', 'GOGN', 'è'),
('好', 'VBG', 'hǎo'),
('坏', 'FGI', 'huài'),
('大', 'DDDD', 'dà'),
('小', 'IH', 'xiǎo'),
('多', 'QQQ', 'duō'),
('少', 'ITR', 'shǎo'),
('长', 'TA', 'cháng'),
('短', 'TDG', 'duǎn'),
('高', 'YM', 'gāo'),
('矮', 'TDTV', 'ǎi'),
('胖', 'EUF', 'pàng'),
('瘦', 'UVHC', 'shòu'),
('重', 'TGJF', 'zhòng'),
('轻', 'LC', 'qīng'),
('快', 'NNW', 'kuài'),
('慢', 'NJLC', 'màn'),
('早', 'JH', 'zǎo'),
('晚', 'JQK', 'wǎn'),
('年', 'RHF', 'nián'),
('月', 'EEE', 'yuè'),
('日', 'JJJJ', 'rì'),
('时', 'JFY', 'shí'),
('分', 'WVB', 'fēn'),
('秒', 'TIIT', 'miǎo'),
('天', 'GDI', 'tiān'),
('地', 'FBN', 'dì'),
('山', 'MMM', 'shān'),
('水', 'IIII', 'shuǐ'),
('火', 'OOOO', 'huǒ'),
('土', 'FFFF', 'tǔ'),
('金', 'QQQQ', 'jīn'),
('木', 'SSSS', 'mù'),
('风', 'MQI', 'fēng'),
('雨', 'FGHY', 'yǔ'),
('雷', 'FLF', 'léi'),
('电', 'JNV', 'diàn'),
('春', 'DWJF', 'chūn'),
('夏', 'DHTU', 'xià'),
('秋', 'TO', 'qiū'),
('冬', 'TUU', 'dōng'),
('东', 'AII', 'dōng'),
('西', 'SGHG', 'xī'),
('南', 'FMUF', 'nán'),
('北', 'UXN', 'běi'),
('前', 'UEJJ', 'qián'),
('后', 'RGK', 'hòu'),
('左', 'DAF', 'zuǒ'),
('右', 'DK', 'yòu'),
('上', 'HHGG', 'shàng'),
('下', 'GHI', 'xià'),
('里', 'JFD', 'lǐ'),
('外', 'QHY', 'wài'),
('中', 'KHK', 'zhōng'),
('内', 'MWI', 'nèi'),
('间', 'UJD', 'jiān'),
('旁', 'UPYB', 'páng'),
('边', 'LPV', 'biān'),
('面', 'DMJD', 'miàn'),
('底', 'YQA', 'dǐ'),
('顶', 'SDMY', 'dǐng'),
('头', 'UDI', 'tóu'),
('尾', 'NTFN', 'wěi'),
('前', 'UEJJ', 'qián'),
('后', 'RGK', 'hòu'),
('始', 'VCK', 'shǐ'),
('终', 'XTU', 'zhōng'),
('开', 'GAK', 'kāi'),
('关', 'UDU', 'guān'),
('进', 'FJPK', 'jìn'),
('出', 'BMK', 'chū'),
('入', 'TYI', 'rù'),
('退', 'VEPI', 'tuì'),
('上', 'HHGG', 'shàng'),
('下', 'GHI', 'xià'),
('升', 'TAK', 'shēng'),
('降', 'BT', 'jiàng'),
('高', 'YM', 'gāo'),
('低', 'WQAY', 'dī'),
('起', 'FHN', 'qǐ'),
('落', 'AIT', 'luò'),
('正', 'GHD', 'zhèng'),
('反', 'RCY', 'fǎn'),
('真', 'FHWU', 'zhēn'),
('假', 'WNHC', 'jiǎ'),
('实', 'PUDU', 'shí'),
('虚', 'HAO', 'xū'),
('是', 'JGHU', 'shì'),
('非', 'DJDD', 'fēi'),
('对', 'CFY', 'duì'),
('错', 'QAJ', 'cuò'),
('好', 'VBG', 'hǎo'),
('坏', 'FGI', 'huài'),
('善', 'UDUK', 'shàn'),
('恶', 'GOGN', 'è'),
('美', 'UGDU', 'měi'),
('丑', 'NFD', 'chǒu'),
('胖', 'EUF', 'pàng'),
('瘦', 'UVHC', 'shòu'),
('强', 'XKJY', 'qiáng'),
('弱', 'XUXU', 'ruò'),
('大', 'DDDD', 'dà'),
('小', 'IH', 'xiǎo'),
('多', 'QQQ', 'duō'),
('少', 'ITR', 'shǎo'),
('长', 'TA', 'cháng'),
('短', 'TDG', 'duǎn'),
('高', 'YM', 'gāo'),
('矮', 'TDTV', 'ǎi'),
('宽', 'PAMQ', 'kuān'),
('窄', 'PWT', 'zhǎi'),
('厚', 'DJB', 'hòu'),
('薄', 'AIGF', 'báo'),
('深', 'IPWS', 'shēn'),
('浅', 'IGT', 'qiǎn'),
('远', 'FQPV', 'yuǎn'),
('近', 'RPK', 'jìn'),
('快', 'NNW', 'kuài'),
('慢', 'NJLC', 'màn'),
('急', 'QVN', 'jí'),
('缓', 'XEFC', 'huǎn'),
('刚', 'MQJH', 'gāng'),
('柔', 'CBTS', 'róu'),
('硬', 'DGJQ', 'yìng'),
('软', 'LRQW', 'ruǎn'),
('冷', 'UWYC', 'lěng'),
('热', 'RVYO', 'rè'),
('温', 'IJLG', 'wēn'),
('凉', 'UYIY', 'liáng'),
('干', 'FGGH', 'gàn'),
('湿', 'IJHG', 'shī'),
('重', 'TGJF', 'zhòng'),
('轻', 'LC', 'qīng'),
('明', 'JEG', 'míng'),
('暗', 'JUJ', 'àn'),
('亮', 'YPMB', 'liàng'),
('黑', 'LFO', 'hēi'),
('白', 'RRRR', 'bái'),
('红', 'XAG', 'hóng'),
('黄', 'AMW', 'huáng'),
('蓝', 'AJTL', 'lán'),
('绿', 'XVIA', 'lǜ'),
('青', 'GEF', 'qīng'),
('紫', 'HXXI', 'zǐ'),
('橙', 'SWGU', 'chéng'),
('粉', 'OWVN', 'fěn'),
('灰', 'DO', 'huī'),
('金', 'QQQQ', 'jīn'),
('银', 'QVEY', 'yín'),
('铜', 'QMGK', 'tóng'),
('铁', 'QRDT', 'tiě'),
('铝', 'QKKQ', 'lǚ'),
('钢', 'QMNA', 'gāng'),
('水', 'IIII', 'shuǐ'),
('火', 'OOOO', 'huǒ'),
('土', 'FFFF', 'tǔ'),
('石', 'DGTG', 'shí'),
('木', 'SSSS', 'mù'),
('草', 'AJJ', 'cǎo'),
('花', 'AWXB', 'huā'),
('树', 'SCF', 'shù'),
('林', 'SS', 'lín'),
('森', 'SSS', 'sēn'),
('竹', 'TTG', 'zhú'),
('果', 'JSI', 'guǒ'),
('菜', 'AE', 'cài'),
('米', 'OYTY', 'mǐ'),
('面', 'DMJD', 'miàn'),
('油', 'IMG', 'yóu'),
('盐', 'FHLF', 'yán'),
('糖', 'OYVK', 'táng'),
('醋', 'SGXJ', 'cù'),
('茶', 'AWSU', 'chá'),
('酒', 'ISGG', 'jiǔ'),
('肉', 'MWWI', 'ròu'),
('鱼', 'QGF', 'yú'),
('鸡', 'CQYG', 'jī'),
('鸭', 'LQYG', 'yā'),
('鹅', 'TRNG', 'é'),
('牛', 'RHK', 'niú'),
('羊', 'UDJ', 'yáng'),
('猪', 'QTFJ', 'zhū'),
('狗', 'QTQK', 'gǒu'),
('猫', 'QTAL', 'māo'),
('马', 'CNNG', 'mǎ'),
('驴', 'CYNT', 'lǘ'),
('骡', 'CLXI', 'luó'),
('车', 'LG', 'chē'),
('船', 'TEMK', 'chuán'),
('飞机', 'FWSM', 'fēi jī'),
('火车', 'TGGL', 'huǒ chē'),
('汽车', 'ILGL', 'qì chē'),
('自行车', 'TFLG', 'zì xíng chē'),
('摩托车', 'CCLG', 'mó tuō chē'),
('电动车', 'LCLG', 'diàn dòng chē'),
('船', 'TEMK', 'chuán'),
('飞机', 'FWSM', 'fēi jī'),
('火车', 'TGGL', 'huǒ chē'),
('汽车', 'ILGL', 'qì chē'),
('自行车', 'TFLG', 'zì xíng chē'),
('摩托车', 'CCLG', 'mó tuō chē'),
('电动车', 'LCLG', 'diàn dòng chē'),
('楼', 'SOVG', 'lóu'),
('房', 'YNYV', 'fáng'),
('屋', 'NGCF', 'wū'),
('舍', 'WFKF', 'shè'),
('院', 'BPFQ', 'yuàn'),
('园', 'LFQV', 'yuán'),
('厅', 'DSK', 'tīng'),
('室', 'PGCF', 'shì'),
('厨', 'DGKF', 'chú'),
('卫', 'BGD', 'wèi'),
('卧', 'AHNH', 'wò'),
('客', 'PTKF', 'kè'),
('餐', 'HQCE', 'cān'),
('堂', 'IPKF', 'táng'),
('馆', 'QNPH', 'guǎn'),
('店', 'YHKD', 'diàn'),
('铺', 'QGEY', 'pù'),
('市', 'YMHJ', 'shì'),
('场', 'FNRT', 'chǎng'),
('街', 'TFFH', 'jiē'),
('路', 'KHTK', 'lù'),
('道', 'UTHP', 'dào'),
('桥', 'STDJ', 'qiáo'),
('港', 'IAWN', 'gǎng'),
('站', 'UHKG', 'zhàn'),
('港', 'IAWN', 'gǎng'),
('站', 'UHKG', 'zhàn'),
('车', 'LG', 'chē'),
('船', 'TEMK', 'chuán'),
('飞机', 'FWSM', 'fēi jī'),
('火车', 'TGGL', 'huǒ chē'),
('汽车', 'ILGL', 'qì chē'),
('自行车', 'TFLG', 'zì xíng chē'),
('摩托车', 'CCLG', 'mó tuō chē'),
('电动车', 'LCLG', 'diàn dòng chē'),
('楼', 'SOVG', 'lóu'),
('房', 'YNYV', 'fáng'),
('屋', 'NGCF', 'wū'),
('舍', 'WFKF', 'shè'),
('院', 'BPFQ', 'yuàn'),
('园', 'LFQV', 'yuán'),
('厅', 'DSK', 'tīng'),
('室', 'PGCF', 'shì'),
('厨', 'DGKF', 'chú'),
('卫', 'BGD', 'wèi'),
('卧', 'AHNH', 'wò'),
('客', 'PTKF', 'kè'),
('餐', 'HQCE', 'cān'),
('堂', 'IPKF', 'táng'),
('馆', 'QNPH', 'guǎn'),
('店', 'YHKD', 'diàn'),
('铺', 'QGEY', 'pù'),
('市', 'YMHJ', 'shì'),
('场', 'FNRT', 'chǎng'),
('街', 'TFFH', 'jiē'),
('路', 'KHTK', 'lù'),
('道', 'UTHP', 'dào'),
('桥', 'STDJ', 'qiáo'),
('港', 'IAWN', 'gǎng'),
('站', 'UHKG', 'zhàn'),
('港', 'IAWN', 'gǎng'),
('站', 'UHKG', 'zhàn'),
('山', 'MMM', 'shān'),
('水', 'IIII', 'shuǐ'),
('火', 'OOOO', 'huǒ'),
('土', 'FFFF', 'tǔ'),
('金', 'QQQQ', 'jīn'),
('木', 'SSSS', 'mù'),
('风', 'MQI', 'fēng'),
('雨', 'FGHY', 'yǔ'),
('雷', 'FLF', 'léi'),
('电', 'JNV', 'diàn'),
('春', 'DWJF', 'chūn'),
('夏', 'DHTU', 'xià'),
('秋', 'TO', 'qiū'),
('冬', 'TUU', 'dōng'),
('东', 'AII', 'dōng'),
('西', 'SGHG', 'xī'),
('南', 'FMUF', 'nán'),
('北', 'UXN', 'běi'),
('前', 'UEJJ', 'qián'),
('后', 'RGK', 'hòu'),
('左', 'DAF', 'zuǒ'),
('右', 'DK', 'yòu'),
('上', 'HHGG', 'shàng'),
('下', 'GHI', 'xià'),
('里', 'JFD', 'lǐ'),
('外', 'QHY', 'wài'),
('中', 'KHK', 'zhōng'),
('内', 'MWI', 'nèi'),
('间', 'UJD', 'jiān'),
('旁', 'UPYB', 'páng'),
('边', 'LPV', 'biān'),
('面', 'DMJD', 'miàn'),
('底', 'YQA', 'dǐ'),
('顶', 'SDMY', 'dǐng'),
('头', 'UDI', 'tóu'),
('尾', 'NTFN', 'wěi'),
('前', 'UEJJ', 'qián'),
('后', 'RGK', 'hòu'),
('始', 'VCK', 'shǐ'),
('终', 'XTU', 'zhōng'),
('开', 'GAK', 'kāi'),
('关', 'UDU', 'guān'),
('进', 'FJPK', 'jìn'),
('出', 'BMK', 'chū'),
('入', 'TYI', 'rù'),
('退', 'VEPI', 'tuì'),
('上', 'HHGG', 'shàng'),
('下', 'GHI', 'xià'),
('升', 'TAK', 'shēng'),
('降', 'BT', 'jiàng'),
('高', 'YM', 'gāo'),
('低', 'WQAY', 'dī'),
('起', 'FHN', 'qǐ'),
('落', 'AIT', 'luò'),
('正', 'GHD', 'zhèng'),
('反', 'RCY', 'fǎn'),
('真', 'FHWU', 'zhēn'),
('假', 'WNHC', 'jiǎ'),
('实', 'PUDU', 'shí'),
('虚', 'HAO', 'xū'),
('是', 'JGHU', 'shì'),
('非', 'DJDD', 'fēi'),
('对', 'CFY', 'duì'),
('错', 'QAJ', 'cuò'),
('好', 'VBG', 'hǎo'),
('坏', 'FGI', 'huài'),
('善', 'UDUK', 'shàn'),
('恶', 'GOGN', 'è'),
('美', 'UGDU', 'měi'),
('丑', 'NFD', 'chǒu'),
('胖', 'EUF', 'pàng'),
('瘦', 'UVHC', 'shòu'),
('强', 'XKJY', 'qiáng'),
('弱', 'XUXU', 'ruò'),
('大', 'DDDD', 'dà'),
('小', 'IH', 'xiǎo'),
('多', 'QQQ', 'duō'),
('少', 'ITR', 'shǎo'),
('长', 'TA', 'cháng'),
('短', 'TDG', 'duǎn'),
('高', 'YM', 'gāo'),
('矮', 'TDTV', 'ǎi'),
('宽', 'PAMQ', 'kuān'),
('窄', 'PWT', 'zhǎi'),
('厚', 'DJB', 'hòu'),
('薄', 'AIGF', 'báo'),
('深', 'IPWS', 'shēn'),
('浅', 'IGT', 'qiǎn'),
('远', 'FQPV', 'yuǎn'),
('近', 'RPK', 'jìn'),
('快', 'NNW', 'kuài'),
('慢', 'NJLC', 'màn'),
('急', 'QVN', 'jí'),
('缓', 'XEFC', 'huǎn'),
('刚', 'MQJH', 'gāng'),
('柔', 'CBTS', 'róu'),
('硬', 'DGJQ', 'yìng'),
('软', 'LRQW', 'ruǎn'),
('冷', 'UWYC', 'lěng'),
('热', 'RVYO', 'rè'),
('温', 'IJLG', 'wēn'),
('凉', 'UYIY', 'liáng'),
('干', 'FGGH', 'gàn'),
('湿', 'IJHG', 'shī'),
('重', 'TGJF', 'zhòng'),
('轻', 'LC', 'qīng'),
('明', 'JEG', 'míng'),
('暗', 'JUJ', 'àn'),
('亮', 'YPMB', 'liàng'),
('黑', 'LFO', 'hēi'),
('白', 'RRRR', 'bái'),
('红', 'XAG', 'hóng'),
('黄', 'AMW', 'huáng'),
('蓝', 'AJTL', 'lán'),
('绿', 'XVIA', 'lǜ'),
('青', 'GEF', 'qīng'),
('紫', 'HXXI', 'zǐ'),
('橙', 'SWGU', 'chéng'),
('粉', 'OWVN', 'fěn'),
('灰', 'DO', 'huī'),
('金', 'QQQQ', 'jīn'),
('银', 'QVEY', 'yín'),
('铜', 'QMGK', 'tóng'),
('铁', 'QRDT', 'tiě'),
('铝', 'QKKQ', 'lǚ'),
('钢', 'QMNA', 'gāng'),
('水', 'IIII', 'shuǐ'),
('火', 'OOOO', 'huǒ'),
('土', 'FFFF', 'tǔ'),
('石', 'DGTG', 'shí'),
('木', 'SSSS', 'mù'),
('草', 'AJJ', 'cǎo'),
('花', 'AWXB', 'huā'),
('树', 'SCF', 'shù'),
('林', 'SS', 'lín'),
('森', 'SSS', 'sēn'),
('竹', 'TTG', 'zhú'),
('果', 'JSI', 'guǒ'),
('菜', 'AE', 'cài'),
('米', 'OYTY', 'mǐ'),
('面', 'DMJD', 'miàn'),
('油', 'IMG', 'yóu'),
('盐', 'FHLF', 'yán'),
('糖', 'OYVK', 'táng'),
('醋', 'SGXJ', 'cù'),
('茶', 'AWSU', 'chá'),
('酒', 'ISGG', 'jiǔ'),
('肉', 'MWWI', 'ròu'),
('鱼', 'QGF', 'yú'),
('鸡', 'CQYG', 'jī'),
('鸭', 'LQYG', 'yā'),
('鹅', 'TRNG', 'é'),
('牛', 'RHK', 'niú'),
('羊', 'UDJ', 'yáng'),
('猪', 'QTFJ', 'zhū'),
('狗', 'QTQK', 'gǒu'),
('猫', 'QTAL', 'māo'),
('马', 'CNNG', 'mǎ'),
('驴', 'CYNT', 'lǘ'),
('骡', 'CLXI', 'luó'),
('车', 'LG', 'chē'),
('船', 'TEMK', 'chuán'),
('飞机', 'FWSM', 'fēi jī'),
('火车', 'TGGL', 'huǒ chē'),
('汽车', 'ILGL', 'qì chē'),
('自行车', 'TFLG', 'zì xíng chē'),
('摩托车', 'CCLG', 'mó tuō chē'),
('电动车', 'LCLG', 'diàn dòng chē'),
('楼', 'SOVG', 'lóu'),
('房', 'YNYV', 'fáng'),
('屋', 'NGCF', 'wū'),
('舍', 'WFKF', 'shè'),
('院', 'BPFQ', 'yuàn'),
('园', 'LFQV', 'yuán'),
('厅', 'DSK', 'tīng'),
('室', 'PGCF', 'shì'),
('厨', 'DGKF', 'chú'),
('卫', 'BGD', 'wèi'),
('卧', 'AHNH', 'wò'),
('客', 'PTKF', 'kè'),
('餐', 'HQCE', 'cān'),
('堂', 'IPKF', 'táng'),
('馆', 'QNPH', 'guǎn'),
('店', 'YHKD', 'diàn'),
('铺', 'QGEY', 'pù'),
('市', 'YMHJ', 'shì'),
('场', 'FNRT', 'chǎng'),
('街', 'TFFH', 'jiē'),
('路', 'KHTK', 'lù'),
('道', 'UTHP', 'dào'),
('桥', 'STDJ', 'qiáo'),
('港', 'IAWN', 'gǎng'),
('站', 'UHKG', 'zhàn'),
('港', 'IAWN', 'gǎng'),
('站', 'UHKG', 'zhàn')
ON CONFLICT (character_val) DO UPDATE SET
    wubi_code = EXCLUDED.wubi_code,
    pinyin = EXCLUDED.pinyin;

SELECT '数据导入完成! 共导入 ' || COUNT(*) || ' 条记录' AS message FROM wubi_characters;
